stages:
  - test
  - lint

# Job to install dependencies and run tests
test:
  image: node:18
  stage: test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
  script:
    - yarn install   # Install project dependencies
    - yarn workspace @actual-app/web test
  cache:
    paths:
      - node_modules/  # Caching node_modules to speed up subsequent builds

# Linter Stage
lint-typescript:
  stage: lint
  image: node:20
  script:
    - yarn install
    - yarn eslint .
  rules:
    - when: always
  allow_failure: false
